#!/bin/sh

HOME=/home/bh

diff .Xresources	$HOME/.Xresources
diff .bashrc		$HOME/.bashrc
diff .conkyrc		$HOME/.conkyrc
diff .profile		$HOME/.profile
diff .vimrc		$HOME/.vimrc
diff .xsession		$HOME/.xsession
diff rc.conf		/etc/rc.conf
diff ttys		/etc/ttys
diff xmonad.hs		$HOME/.xmonad/xmonad.hs
diff xorg.conf		/etc/X11/xorg.conf
